language: generic
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs-snapshot
script: emacs -batch -l add-hooks.el -l add-hooks-test.el -f ert-run-tests-batch-and-exit
